#
# Module manifest for module 'Greenroom'
#
# Generated by: Tyler Vigario
#
# Generated on: 09/25/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Greenroom.psm1'

# Version number of this module.
ModuleVersion = '0.4.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '518689f0-0456-4317-a7e1-daa1eaf66161'

# Author of this module
Author = 'Tyler Vigario'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2026 Tyler Vigario. AGPL-3.0-or-later.'

# Description of the functionality provided by this module
Description = 'Always-on Claude Code Remote Control sessions on Windows. Each instance starts hidden at logon, stays supervised, and is revealed on demand with its full live scrollback. Windows-only: depends on Task Scheduler, Windows Terminal and user32.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Greenroom.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-GreenroomInstance', 'Show-GreenroomSession', 
               'Hide-GreenroomSession', 'Restart-GreenroomSession', 
               'Start-GreenroomSession', 'Stop-GreenroomSession',
               'Switch-GreenroomSession', 
               'Uninstall-GreenroomInstance', 'Install-GreenroomInstance', 
               'Update-GreenroomInstance'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'claude','remote-control','windows','session','automation'

        # A URL to the license for this module.
        LicenseUri = 'https://www.gnu.org/licenses/agpl-3.0.en.html'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/TylerVigario/greenroom-win'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/TylerVigario/greenroom-win/main/assets/greenroom.png'

        # ReleaseNotes of this module
        ReleaseNotes = '#### Features
- session: stop an instance and leave it stopped (#45)
- session: pin an instance''s conversation by id (#43)
#### Bug Fixes
- ci: commit the tag ruleset payload (#48)
- package: no company owns this module (#51)
- release: name the App that actually exists (#50)
- release: point the release machinery at the repository''s new owner (#46)
#### Documentation
- readme: say when a stopped instance actually comes back (#47)
#### Continuous Integration
- watch the action pins with dependabot (#49)

Full changelog: https://github.com/TylerVigario/greenroom-win/releases/tag/v0.4.0'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

