#
# Module manifest for module 'Greenroom'
#
# Generated by: Tyler Vigario
#
# Generated on: 10/01/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Greenroom.psm1'

# Version number of this module.
ModuleVersion = '0.7.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '518689f0-0456-4317-a7e1-daa1eaf66161'

# Author of this module
Author = 'Tyler Vigario'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2026 Tyler Vigario. AGPL-3.0-or-later.'

# Description of the functionality provided by this module
Description = 'Always-on Claude Code Remote Control sessions on Windows. Each instance starts hidden at logon, stays supervised, and is revealed on demand with its full live scrollback. Windows-only: depends on Task Scheduler, Windows Terminal and user32.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Greenroom.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-GreenroomInstance', 'Show-GreenroomSession', 
               'Hide-GreenroomSession', 'Restart-GreenroomSession', 
               'Start-GreenroomSession', 'Stop-GreenroomSession', 
               'Switch-GreenroomSession', 'Uninstall-GreenroomInstance', 
               'Install-GreenroomInstance', 'Update-GreenroomInstance'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'claude','remote-control','windows','session','automation'

        # A URL to the license for this module.
        LicenseUri = 'https://www.gnu.org/licenses/agpl-3.0.en.html'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/TylerVigario/greenroom-win'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/TylerVigario/greenroom-win/main/assets/greenroom.png'

        # ReleaseNotes of this module
        ReleaseNotes = '#### Features
- release: publish the package with provenance (#67)
#### Bug Fixes
- ci: forbid moving a published tag (#58)
- install: an explicit -ClaudeExe is that path or nothing (#84)
- install: store the working directory as the launcher will land (#76)
- install: refuse an instance name ending in a dot (#72)
- launcher: bound launch.log the way watchdog.log is bounded (#85)
- release: drop the pre-flight gallery key check (#68)
- release: have GitHub construct the version commit (#66)
- release: publish before the version is recorded (#65)
- session: stop only shells running greenroom''s scripts (#91)
- session: guard only against stopping greenroom''s own session (#89)
- session: stop only the session greenroom started (#88)
- session: list only the sessions greenroom started (#86)
- session: count a process as stopped only when it is gone (#81)
- session: escalate in the shell greenroom resolves, not pwsh by name (#79)
- session: elevate before looking for an elevated session (#75)
- trust: back up ~/.claude.json only when writing it, and keep five (#83)
- trust: read and write Claude Code''s files as UTF-8 without a BOM (#80)
- trust: decide what is already trusted from the parsed file (#74)
- uninstall: guard the session it runs in, and elevated instances (#77)
- uninstall: refuse a name that is not an instance''s (#71)
- watchdog: close only the window greenroom recorded (#90)
- watchdog: adopt only this instance''s own session (#87)
- watchdog: quote the paths it hands Windows Terminal (#78)
- watchdog: close only windows titled exactly as this instance''s session (#73)
#### Documentation
- provisioning: drop a directory installing no longer writes (#69)
- release: the release environment no longer needs a reviewer (#70)
- add issue and pull request templates (#62)
- add a security policy (#61)
#### Tests
- install: trip on anything install would do, in the tests that expect it to stop (#82)
#### Continuous Integration
- block a merge on code scanning alerts (#63)
- pin cocogitto by checksum (#60)
- pin actions by commit (#59)

Full changelog: https://github.com/TylerVigario/greenroom-win/releases/tag/v0.7.0'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

